### ISSUE TITLE
imagehomog not working for the image

### ISSUE THREAD

**Issue by Addhi86** [YouriT/matlab-speech#1]
Hello

I am trying to use `imagehomog` function from the toolbox but unfortunately, i am not getting the correct output
here is my code

```
 im = imread('cameraman.tif');
n = [0;0;-1];
d = Inf
   theta = 60*pi/180;

   R = [ 1     1           0 ;
       0  cos(theta) -sin(theta);
       0  sin(theta)  cos(theta)];

   t = [0;0;0];

  K=[300 0    0;
        0    300 0;
        0    0    1];

  H=K*R/K-1/d*K*t*n'*K;

 img=imagehomog((im),H','c');
 figure;imshow(img)
```
I get this at the output
![image](https://cloud.githubusercontent.com/assets/22164098/23047546/a601167e-f504-11e6-955a-f03b3bbf082f.png)

Can you please suggest me how can i fix it?

**Comment by YouriT** [comment]
Sorry but I haven't went into this project for more that 3years and it was a study project, hence I'm not maintaining it.
